:sourcedir: src/main/java/org/wysko/midis2jam2

= Adding new instruments

_Note: this document was written when the program was being developed in Java.
While the content of the document is still accurate, it does not have examples in Kotlin.
Kotlin equivalents of the Java code presented are to be used._

Here is an overview of how to add a new instrument to midis2jam2.

== Overview of instruments

Every single instrument in midis2jam2 is a subclass of link:{sourcedir}/instrument/Instrument.kt[`Instrument`].
This class contains the necessary logic that all instruments in midis2jam2 should implement.
`Instrument` also contains the necessary node tree structure for proper movement.
Subclasses of `Instrument` shall use this node tree.

`Instrument` also has a field for visibility (`isVisible`).
I've already provided an implementation of automatically setting this variable—depending on the type of instrument, it is implemented in the appropriate subclass.

There are three primary main subclasses of `Instrument`.

* link:{sourcedir}/instrument/SustainedInstrument.kt[`SustainedInstrument`]
** Any instrument that depends on knowing the `MidiNoteOffEvent` for each note.
* link:{sourcedir}/instrument/DecayedInstrument.kt[`DecayedInstrument`]
** Any instrument that solely animates on just the `MidiNoteOnEvent`.
* link:{sourcedir}/instrument/family/percussion/drumset/PercussionInstrument.kt[`PercussionInstrument`]
** Any instrument that is on the percussion channel.
Instruments that are not a part of the core drum set (kick drum, snare drum, hi-hat, cymbals) are of type link:{sourcedir}/instrument/family/percussion/drumset/NonDrumSetPercussion.kt[`NonDrumSetPercussion`].
Note: at this time, midis2jam2 cannot differentiate between percussion kits.
Therefore, only the standard kit instruments are recognized.

=== What class should I pick?

If your instrument appears on channel 10 (the percussion channel), you should extend `NonDrumSetPercussion` (I've already implemented all the drum set instruments, so there should be nothing more to implement here).

If your instrument is a melodic patch, either extend `SustainedInstrument` or `DecayedInstrument` depending on how you want the instrument to animate.

Here's a comprehensive list of classes you can extend (you can read the JavaDoc of each to learn more):

* Instrument
* SustainedInstrument
* DecayedInstrument
* MonophonicInstrument
* WrappedOctaveSustained
* FrettedInstrument
* OctavePercussion
* OneDrumOctave
* TwelveDrumOctave
* KeyedInstrument
* HandedInstrument
* StringFamilyInstrument

_Why can't I just extend `Instrument`?_ You sure can.
However, there is a lot of code written that applies to many instruments that are not in `Instrument` and are in subclasses.
If you choose a more specific subclass, you will reduce the amount of boilerplate code needed.

== Adding a new instrument

=== What are the implementation requirements?

Each instrument must do these things:

* Define a constructor that accepts an instance of `Midis2jam2` and a `List<MidiChannelSpecificEvent>` as parameters.
* Implement `moveForMultiChannel(float delta)` (_does not apply to percussion instruments_).
* Implement `tick(double time, float delta)`.

Abstract classes shall not implement these methods (e.g., `SustainedInstrument`).
It is up to final children classes to implement these (e.g., `Trumpet`).

Some subclasses may require instruments to implement more methods than these (or provide more parameters in the call to super); at a minimum all instruments will fulfill these requirements.

==== Constructor

The constructor should generally follow this structure (in this example, the instrument is `Mayonnaise`, because mayonnaise is indeed an instrument):

[source,java]
----
public Mayonnaise(Midis2jam2 context, List<MidiChannelSpecificEvent> events) {
	super(context, events);
	...
}
----

Anything else that needs to be initialized when instrument is first constructed (e.g., loading 3D models, positioning objects, etc.) should occur after the call to super.
The example call to super here may not be the same depending on which class you are extending.

==== `moveForMultiChannel`

`moveForMultiChannel` tells midi2jam2 how to move this instrument when there is more than one instance of the instrument on the stage at any given time.
To know this instrument's current position within the stack of currently visible instruments, use `indexForMoving(delta)` as your index.
To adjust the position, modify the instrument's `offsetNode` location.
*Only move this node for offsetting with multiple instances of an instrument.*

[source,java]
----
@Override
protected void moveForMultiChannel(float delta) {
	offsetNode.setLocalTranslation(20f * indexForMoving(delta), 0, 0);
}
----

The above example moves the Mayonnaise 20 units on +X for each position.
For example, if there was only one Mayonnaise, it would not be moved (since the index starts at 0).
The second Mayonnaise would be moved along +X by 20 units.
The third would be moved by 40.

==== `tick`

The `tick` method is called on every frame.
Therefore, the bulk of your animation code will reside here.
If your superclass contains some code that also needs to run, **you should call super**!
Later examples will give a clearer picture as to what exactly is written here.

Here is a blank example.
It does nothing.

[source,java]
----
protected void tick(double time, float delta) {
	super(time, delta); // Only call super if the superclass contains some code in its own `tick` implementation.
	...
}
----

Replace the ellipsis with your own logic.

==== Simple example

The following is the bare minimum needed to have a `SustainedInstrument`.
It does nothing.
The example assumes it is located in the `org.wysko.midis2jam2.instrument.family.brass` package, just for example.

[source,java]
----
package org.wysko.midis2jam2.instrument.family.brass;

import org.wysko.midis2jam2.Midis2jam2;
import org.wysko.midis2jam2.instrument.SustainedInstrument;
import org.wysko.midis2jam2.midi.MidiChannelSpecificEvent;

import java.util.List;

public class Mayonnaise extends SustainedInstrument {
    public Mayonnaise(Midis2jam2 context, List<MidiChannelSpecificEvent> events) {
        super(context, events);
    }

    @Override
    protected void moveForMultiChannel(float delta) {
        offsetNode.setLocalTranslation(20f * indexForMoving(delta), 0, 0);
    }

    @Override
    public void tick(double time, float delta) {

    }
}
----

=== Analyzing some examples

I learn best by example.
So, let's go over a few examples.

==== `NonDrumSetPercussion`

Let's look at how to add a percussion instrument.
We'll look at the `Maracas` for example.
I've removed the JavaDocs in this example for conciseness.

[source,java]
----
package org.wysko.midis2jam2.instrument.family.percussion;

import com.jme3.math.Quaternion;
import com.jme3.scene.Node;
import com.jme3.scene.Spatial;
import org.jetbrains.annotations.NotNull;
import org.wysko.midis2jam2.Midis2jam2;
import org.wysko.midis2jam2.instrument.family.percussion.drumset.NonDrumSetPercussion;
import org.wysko.midis2jam2.instrument.family.percussive.Stick;
import org.wysko.midis2jam2.midi.MidiNoteOnEvent;
import org.wysko.midis2jam2.world.Axis;

import java.util.List;

import static org.wysko.midis2jam2.util.Utils.rad;

public class Maracas extends NonDrumSetPercussion {

	@NotNull
	private final Spatial leftMaraca;

	@NotNull
	private final Spatial rightMaraca;

	protected Maracas(Midis2jam2 context, List<MidiNoteOnEvent> hits) {
		super(context, hits);

		/* Load maracas */
		leftMaraca = context.loadModel("Maraca.obj", "Maraca.bmp");
		rightMaraca = context.loadModel("Maraca.obj", "Maraca.bmp");

		/* Create nodes for maracas */
		var leftMaracaNode = new Node();
		leftMaracaNode.attachChild(leftMaraca);

		var rightMaracaNode = new Node();
		rightMaracaNode.attachChild(rightMaraca);

		/* Tilt maracas */
		leftMaracaNode.setLocalRotation(new Quaternion().fromAngles(0, 0, 0.2F));
		rightMaracaNode.setLocalRotation(new Quaternion().fromAngles(0, 0, -0.2F));

		/* Positioning */
		rightMaracaNode.setLocalTranslation(5, -1, 0);
		instrumentNode.setLocalTranslation(-13, 65, -41);
		instrumentNode.setLocalRotation(new Quaternion().fromAngles(rad(-Stick.MAX_ANGLE / 2), 0, 0));

		/* Attach maracas */
		instrumentNode.attachChild(leftMaracaNode);
		instrumentNode.attachChild(rightMaracaNode);
	}

	@Override
	public void tick(double time, float delta) {
		super.tick(time, delta);

		/* Animate left maraca */
		var status = handleStick(context, leftMaraca, time, delta, hits, Stick.STRIKE_SPEED, Stick.MAX_ANGLE, Axis.X);

		/* Override handleStick culling the left maraca */
		leftMaraca.setCullHint(Spatial.CullHint.Dynamic);

		/* Copy rotation to right maraca */
		rightMaraca.setLocalRotation(new Quaternion().fromAngles(status.getRotationAngle(), 0, 0));

	}
}
----

Let's break this down.
I'll skip the package and import statements since these are automatically handled by your IDE.

We start by declaring the class.

[source,java]
----
public class Maracas extends NonDrumSetPercussion {
----

We define some fields in our class that will hold the 3D models of each maraca.
As a null-safe measure, we annotate them as `@NotNull`.

[source,java]
----
/**
 * The left maraca.
 */
@NotNull
private final Spatial leftMaraca;

/**
 * The right maraca.
 */
@NotNull
private final Spatial rightMaraca;
----

We then declare our constructor and call super with the appropriate parameters.

[source,java]
----
protected Maracas(Midis2jam2 context, List<MidiNoteOnEvent> hits) {
    super(context, hits);
----

Then we set up the 3D models, node tree, and positioning.
There are comments here explaining what each section does.

[source,java]
----
/* Load maracas */
leftMaraca = context.loadModel("Maraca.obj", "Maraca.bmp");
rightMaraca = context.loadModel("Maraca.obj", "Maraca.bmp");

/* Create nodes for maracas */
var leftMaracaNode = new Node();
leftMaracaNode.attachChild(leftMaraca);

var rightMaracaNode = new Node();
rightMaracaNode.attachChild(rightMaraca);

/* Tilt maracas */
leftMaracaNode.setLocalRotation(new Quaternion().fromAngles(0, 0, 0.2F));
rightMaracaNode.setLocalRotation(new Quaternion().fromAngles(0, 0, -0.2F));

/* Positioning */
rightMaracaNode.setLocalTranslation(5, -1, 0);
instrumentNode.setLocalTranslation(-13, 65, -41);
instrumentNode.setLocalRotation(new Quaternion().fromAngles(rad(-Stick.MAX_ANGLE / 2), 0, 0));

/* Attach maracas */
instrumentNode.attachChild(leftMaracaNode);
instrumentNode.attachChild(rightMaracaNode);
----

We do not need to implement `moveForMultiChannel` because this is a percussion instrument.

We then implement the `tick` method.

[source,java]
----
@Override
public void tick(double time, float delta) {
	super.tick(time, delta);

	/* Animate left maraca */
	var status = Stick.handleStick(context, leftMaraca, time, delta, hits, Stick.STRIKE_SPEED, Stick.MAX_ANGLE, Axis.X);

	/* Override handleStick culling the left maraca */
	leftMaraca.setCullHint(Spatial.CullHint.Dynamic);

	/* Copy rotation to right maraca */
	rightMaraca.setLocalRotation(new Quaternion().fromAngles(status.getRotationAngle(), 0, 0));
}
----

We begin by calling super.
This is important because the superclass(es) are handling visibility of the instrument.
Then, we animate `leftMaraca`.
We do this by calling `Stick.handleStick` from link:{sourcedir}/instrument/family/percussive/Stick.kt[`Stick`].
This method is your one-stop shop for animating any sort of stick striking something, or anything else that has a remotely similar animation.
Use this method whenever possible for animating things that strike.

`handleStick` causes a few side effects when applying it to a `Node` or `Spatial`.
One of these is that it will hide the stick when it is not actively striking or recoiling.
In this case, we do not want this behavior because `NonDrumSetPercussion` handles this for us (it sets the cull hint of a node higher up in the tree).
So, we override this side effect by explicitly resetting `leftMaraca` to be visible.

Because the maraca has two maracas, we need to also apply this to `rightMaraca`.
We simply set the rotation of `rightMaraca` to be the same as `leftMaraca`.
`Stick.handleStick` returns a `StickStatus` which contains `getRotationAngle()` which is the new rotation angle after the method has completed.

==== `AltoSax`

The `AltoSax` and other `link:{sourcedir}/instrument/family/reed/sax/AltoSax.kt[MonophonicInstrument]`​s require special code for handling polyphony.
Because the instrument is inherently monophonic (you can only play one note at a time), representing the degrees of polyphony can only be done by temporarily spawning "clones" of the saxophone.
`MonophonicInstrument` defines an algorithm for assigning notes to clones (`calculateClones`).
Classes that extend this and call super in the constructor will have clones calculated.

Let's look at the class.

[source,java]
----
package org.wysko.midis2jam2.instrument.family.reed.sax;

import com.jme3.material.Material;
import com.jme3.math.ColorRGBA;
import com.jme3.math.Quaternion;
import com.jme3.scene.Node;
import org.wysko.midis2jam2.Midis2jam2;
import org.wysko.midis2jam2.instrument.algorithmic.PressedKeysFingeringManager;
import org.wysko.midis2jam2.instrument.clone.Clone;
import org.wysko.midis2jam2.midi.MidiChannelSpecificEvent;

import java.util.List;

import static org.wysko.midis2jam2.util.Utils.rad;

public class AltoSax extends Saxophone {

	public static final PressedKeysFingeringManager FINGERING_MANAGER = PressedKeysFingeringManager.from(AltoSax.class);

	private static final float STRETCH_FACTOR = 0.65F;

	public AltoSax(Midis2jam2 context, List<MidiChannelSpecificEvent> events) throws ReflectiveOperationException {
		super(context, events, AltoSaxClone.class, FINGERING_MANAGER);
		groupOfPolyphony.setLocalTranslation(-32, 46.5F, -50);
	}

	public class AltoSaxClone extends SaxophoneClone {

		public AltoSaxClone() {
			super(AltoSax.this, STRETCH_FACTOR);

			var shinyHornSkin = context.reflectiveMaterial("Assets/HornSkin.bmp");
			var black = new Material(context.getAssetManager(), "Common/MatDefs/Misc/Unshaded.j3md");
			black.setColor("Color", ColorRGBA.Black);

			this.body = context.getAssetManager().loadModel("Assets/AltoSaxBody.fbx");
			this.bell.attachChild(context.getAssetManager().loadModel("Assets/AltoSaxHorn.obj"));

			var bodyNode = ((Node) body);

			bodyNode.getChild(0).setMaterial(shinyHornSkin);
			bodyNode.getChild(1).setMaterial(black);
			bell.setMaterial(shinyHornSkin);

			modelNode.attachChild(this.body);
			modelNode.attachChild(bell);

			/* The bell has to be moved down to attach to the body */
			bell.move(0, -22, 0);

			animNode.setLocalTranslation(0, 0, 20);
			highestLevel.setLocalRotation(new Quaternion().fromAngles(rad(13), rad(75), 0));
		}
	}
}
----

Again, we break it down and analyze each component.

We declare the class and its superclass. `Saxophone` is a direct subclass of `MonophonicInstrument`; it only provides the common behavior of all saxophones: the `moveForMultiChannel`.
Because it is defined there, we do not need to define it here.

[source,java]
----
public class AltoSax extends Saxophone {
----

We then call `PressedKeysFingeringManager.from(Class<? extends Instrument>)` to collect the fingering manager for `AltoSax`.
The method will read link:src/main/resources/instrument_mapping.xml[instrument_mapping.xml] and collect the fingerings for the XML `instrument` that has the same `name` as the `simpleName` of the class.

[source,java]
----
public static final PressedKeysFingeringManager FINGERING_MANAGER = PressedKeysFingeringManager.from(AltoSax.class);
----

We then define how stretchy the bell is.

[source,java]
----
private static final float STRETCH_FACTOR = 0.65F;
----

We then define the constructor and initialize the position.
Notice the throws to `ReflectiveOperationException`—this is thrown whenever the constructor of a `Clone` throws an exception.

[source,java]
----
public AltoSax(Midis2jam2 context, List<MidiChannelSpecificEvent> events) throws ReflectiveOperationException {
    super(context, events, AltoSaxClone.class, FINGERING_MANAGER);
    groupOfPolyphony.setLocalTranslation(-32, 46.5F, -50);
}
----

We then define `AltoSaxClone` as a subclass of `SaxophoneClone`.
This is a subclass of `Clone` but contains some shared code across all types of saxophones (loading keys and moving clones in a circle for polyphony).
Let's take a quick look at that first:

[source,java]
----
package org.wysko.midis2jam2.instrument.family.reed.sax;

import com.jme3.math.Quaternion;
import org.wysko.midis2jam2.instrument.clone.UpAndDownKeyClone;
import org.wysko.midis2jam2.util.MatType;

import static org.wysko.midis2jam2.util.Utils.rad;

public abstract class SaxophoneClone extends UpAndDownKeyClone {

	private static final int NUMBER_OF_KEYS = 20;
	private static final float ROTATION_FACTOR = 0.1f;

	protected SaxophoneClone(Saxophone parent, float stretchFactor) {
		super(NUMBER_OF_KEYS, parent, ROTATION_FACTOR, stretchFactor);

		for (var i = 0; i < keyCount; i++) {
			keysUp[i] = parent.context.loadModel(String.format("AltoSaxKeyUp%d.obj", i),
					"HornSkinGrey.bmp", MatType.REFLECTIVE, 0.9f);

			keysDown[i] = parent.context.loadModel(String.format("AltoSaxKeyDown%d.obj", i),
					"HornSkinGrey.bmp", MatType.REFLECTIVE, 0.9f);
		}

		attachKeys();
	}

	@Override
	protected void moveForPolyphony() {
		offsetNode.setLocalRotation(new Quaternion().fromAngles(0, rad(25f * indexForMoving()), 0));
	}
}
----

Notice the implementation of `moveForPolyphony`.
This is required for all classes that extend `Clone`.
However, instead of writing this implementation in each saxophone type class, we extract this common behavior to a superclass.

Back to `AltoSaxClone`:

[source,java]
----
public class AltoSaxClone extends SaxophoneClone {
    public AltoSaxClone() {
    	super(AltoSax.this, STRETCH_FACTOR);

    	var shinyHornSkin = context.reflectiveMaterial("Assets/HornSkin.bmp");
    	var black = new Material(context.getAssetManager(), "Common/MatDefs/Misc/Unshaded.j3md");
    	black.setColor("Color", ColorRGBA.Black);

    	this.body = context.getAssetManager().loadModel("Assets/AltoSaxBody.fbx");
    	this.bell.attachChild(context.getAssetManager().loadModel("Assets/AltoSaxHorn.obj"));

    	var bodyNode = ((Node) body);

    	bodyNode.getChild(0).setMaterial(shinyHornSkin);
    	bodyNode.getChild(1).setMaterial(black);
    	bell.setMaterial(shinyHornSkin);

    	modelNode.attachChild(this.body);
    	modelNode.attachChild(bell);

    	/* The bell has to be moved down to attach to the body */
    	bell.move(0, -22, 0);

    	animNode.setLocalTranslation(0, 0, 20);
    	highestLevel.setLocalRotation(new Quaternion().fromAngles(rad(13), rad(75), 0));
    }
}
----

Here, we load the models for the Alto Sax and initialize it.

Back to the fingering manager.
Here's a small snippet from `instrument_mapping.xml` for the `AltoSax`:

[source,xml]
----
<instrument name="AltoSax" mapping-type="pressed_keys">
        <mapping>
            <map note="80">
                <key>2</key>
                <key>1</key>
                <key>0</key>
                <key>11</key>
            </map>
            <map note="79">
                <key>2</key>
                <key>1</key>
                <key>11</key>
            </map>
            <map note="78">
                <key>2</key>
                <key>1</key>
            </map>
            <map note="77">
                <key>2</key>
            </map>
            ...
    </mapping>
</instrument>
----

It has a list of `map`​s that define a list of `key`​s that should be pressed given a `note`.

