= 🎵 midis2jam2

image:https://img.shields.io/github/v/release/wyskoj/midis2jam2[]
image:https://img.shields.io/github/downloads/wyskoj/midis2jam2/total[GitHub Downloads (all assets, all releases)]
image:https://img.shields.io/codacy/grade/2685466ed5224e58b52d707a64737352[Codacy grade]
image:https://img.shields.io/github/license/wyskoj/midis2jam2[]
image:https://img.shields.io/github/issues-closed/wyskoj/midis2jam2[]

midis2jam2 is a remaster of MIDIJam, a 3D MIDI file visualizer.
It plays and animates any MIDI file with a 3D virtual band.

It is written in Kotlin/JVM and uses jMonkeyEngine for graphics.

== 🖥️ Installation

Install midis2jam2 with the https://github.com/wyskoj/midis2jam2/releases[appropriate installer for the latest version].

== 💾 Building

midis2jam2 requires JDK 17 to be on your machine's PATH to build and run.
https://www.azul.com/downloads/#zulu[Azul Zulu 17] is known to work well.

[source,bash]
----
$ git clone https://github.com/wyskoj/midis2jam2
$ cd midis2jam2 && ./gradlew run
----

== ⁉️ Support

Find guides and answers to common questions on the https://wyskoj.github.io/midis2jam2-docs/[documentation site]. For support, visit https://github.com/wyskoj/midis2jam2/discussions[the discussions page].

== ✴️ Acknowledgements

* http://www.gamesbyscott.com/midijam.htm[MIDIJam]
* https://jmonkeyengine.org/[jMonkeyEngine]

== ⚖️ License

midis2jam2 © MMXXI–MMXXVI Jacob Wysko. The software is licensed under the https://github.com/wyskoj/midis2jam2/blob/master/LICENSE[GNU General Public License v3.0] and comes with absolutely no warranty.

Some assets Copyright © 2007 Scott Haag  (used with permission).

View the _About_ screen in the application for contribution attributions.

SoundFont is a registered trademark of E-mu Systems, Inc.
