= midis2jam2

*midis2jam2* is a remaster, sequel, v2.0, etc., to MIDIJam, a MIDI file visualizer made by Scott Haag, last updated in 2007.

midis2jam2 aims to faithfully recreate MIDIJam while fixing bugs and completing the GM-1 implementation.

Future versions may add extended features, such as custom graphics, real-time MIDI visualization, and others.

== Running
Download and build from source.
----
$ git clone https://github.com/wyskoj/midis2jam2
$ cd midis2jam2
$ gradlew shadowjar
----
Copy the `.jar` from `build/libs` and `Midicsv.exe` to a new folder. Then run the program.

----
java -jar midis2jam2.jar your_midi_file.mid
----

== FAQ

=== How do I change the soundfont?

midis2jam2 does not handle the playback of MIDI files, unless a preferred MIDI synth is not active on your machine (the program reverts to the internal Java MIDI synth). For Windows, I recommend  https://coolsoft.altervista.org/en/virtualmidisynth[VirtualMIDISynth]. The preferred MIDI synth device can be adjusted by editing https://github.com/wyskoj/midis2jam2/blob/master/src/main/java/org/wysko/midis2jam2/Midis2jam2.java#L133[the main class] and rebuilding.

In the future, this process will be simpler.

=== I'm on MacOS/Linux and I can't run `midicsv.exe`.

If you can use `apt`, run
----
$ sudo apt install midicsv
----
If you can use `brew`, run
----
$ brew install midicsv
----
Otherwise, download and extract https://www.fourmilab.ch/webtools/midicsv/midicsv-1.1.tar.gz[the source], then run
----
$ make
----
Then copy `midicsv` to the same folder where you execute the `.jar` file.

For either method, ensure https://github.com/wyskoj/midis2jam2/blob/master/src/main/java/org/wysko/midis2jam2/midi/MidiFile.java#L51[this line] is prepended with a `./` if `midicsv` is a file (manual build), otherwise nothing (`apt` or `brew`).

== Contributing

Fork and make a pull request to directly make changes. Open an issue to request features and report bugs. Please ensure you https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f[write good issues].

== License

* midis2jam2 is released under the http://www.gnu.org/licenses/gpl.html[GNU General Public License 3].
* Assets Copyright &copy; 2007 Scott Haag.
* https://asdf.com[Test MIDI files] Copyright &copy; various authors. 
