package org.wysko.midis2jam2.particle;

/**
 * Generates particles.
 */
public interface ParticleGenerator {
	/**
	 * Updates the animation of this generator.
	 *
	 * @param time   the current time, in seconds
	 * @param delta  the amount of time since the last frame
	 * @param active true if this particle generator should be generating
	 */
	void tick(double time, float delta, boolean active);
	
	/**
	 * A particle as generated by a {@link ParticleGenerator}.
	 */
	interface Particle {
		
		/**
		 * Update animation.
		 *
		 * @param delta the amount of time since the last frame
		 * @return true if this particle needs to remain, false otherwise
		 */
		boolean tick(float delta);
	}
}
