/*
 * Copyright (C) 2026 Jacob Wysko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

package org.wysko.midis2jam2.assettools

import java.io.File

const val CATALOG_PACKAGE = "org.wysko.midis2jam2.assets"
private const val INDENT = "    "

/**
 * Generates the typed asset catalog: one nested `object` per folder and one `val` per asset, so that code says
 * `Models.Reed.Sax.Alto.Body` instead of a path string and a missing asset is a compile error.
 *
 * Numbered runs (`KeyUp0` … `KeyUp19`) additionally get a list (`KeyUp`), for code that builds one spatial per
 * file. An `AssetCatalog` object lists every entry, for tests that check them all.
 */
class CatalogWriter(private val entries: List<CatalogEntry>) {

    private class Scope(val path: String) {
        val scopes = sortedMapOf<String, Scope>()
        val values = sortedMapOf<String, String>(Naming.naturalOrder)
        val sources = mutableMapOf<String, String>()
    }

    private val roots: Map<AssetKind, Scope> = AssetKind.entries.associateWith { Scope(it.rootObject) }
    private val qualifiedNames: Map<AssetKind, MutableList<String>> = AssetKind.entries.associateWith { mutableListOf() }

    init {
        entries.sortedWith(compareBy({ it.kind }, { it.assetPath })).forEach(::add)
        roots.values.forEach(::checkScope)
    }

    private fun add(entry: CatalogEntry) {
        var scope = roots.getValue(entry.kind)
        var qualified = entry.kind.rootObject
        for (folder in entry.segments.dropLast(1)) {
            val id = Naming.identifier(folder)
            claim(scope, id, "$folder/")
            scope = scope.scopes.getOrPut(id) { Scope("${scope.path}/$folder") }
            qualified += ".$id"
        }
        val file = entry.segments.last()
        val id = Naming.identifier(file)
        claim(scope, id, file)
        if (id in scope.scopes) collision(scope, id)
        scope.values[id] = entry.assetPath
        qualifiedNames.getValue(entry.kind) += "$qualified.$id"
    }

    /** Records that [source] maps to [id] in [scope], failing if a different name already does. */
    private fun claim(scope: Scope, id: String, source: String) {
        val previous = scope.sources.putIfAbsent(id, source)
        if (previous != null && previous != source) collision(scope, id)
    }

    private fun checkScope(scope: Scope) {
        val names = scope.values.keys + scope.scopes.keys
        names.groupBy { it.lowercase() }.values.firstOrNull { it.size > 1 }?.let {
            throw AssetToolException(
                "${scope.path}: ${it.joinToString(" and ")} differ only in case, which breaks on case-insensitive " +
                    "file systems"
            )
        }
        Naming.families(scope.values.keys).forEach { if (it.name in names) collision(scope, it.name) }
        scope.scopes.values.forEach(::checkScope)
    }

    private fun collision(scope: Scope, id: String): Nothing = throw AssetToolException(
        "${scope.path}: more than one asset or folder would be called '$id' in the catalog; rename one of them"
    )

    /** The catalog's Kotlin source. */
    fun render(): String = buildString {
        appendLine("// Generated by :asset-tools from sharedAssets. Do not edit; see docs/ASSETS.md.")
        appendLine()
        appendLine("package $CATALOG_PACKAGE")
        for (kind in AssetKind.entries) {
            appendLine()
            renderScope(kind.rootObject, roots.getValue(kind), kind.type, 0)
        }
        appendLine()
        appendLine("/** Every catalogued asset, for checks that cover them all. */")
        appendLine("object AssetCatalog {")
        for (kind in AssetKind.entries) {
            appendList(kind.rootObject.lowercase(), kind.type, qualifiedNames.getValue(kind), 1)
        }
        appendLine("}")
    }

    private fun StringBuilder.renderScope(name: String, scope: Scope, type: String, depth: Int) {
        val indent = INDENT.repeat(depth)
        appendLine("${indent}object $name {")
        for ((id, path) in scope.values) {
            appendLine("$indent${INDENT}val $id: $type = $type(\"$path\")")
        }
        for (family in Naming.families(scope.values.keys)) {
            appendList(family.name, type, family.members, depth + 1)
        }
        for ((id, child) in scope.scopes) {
            renderScope(id, child, type, depth + 1)
        }
        appendLine("$indent}")
    }

    private fun StringBuilder.appendList(name: String, type: String, items: List<String>, depth: Int) {
        val indent = INDENT.repeat(depth)
        if (items.isEmpty()) {
            appendLine("${indent}val $name: List<$type> = emptyList()")
            return
        }
        appendLine("${indent}val $name: List<$type> = listOf(")
        items.forEach { appendLine("$indent$INDENT$it,") }
        appendLine("$indent)")
    }

    /** Writes the catalog under [outDir] (a Kotlin source root), replacing whatever was there. */
    fun write(outDir: File) {
        outDir.deleteRecursively()
        val file = File(outDir, CATALOG_PACKAGE.replace('.', '/') + "/AssetCatalog.kt")
        file.parentFile.mkdirs()
        file.writeText(render())
    }
}
