/*
 * Copyright (C) 2025 Jacob Wysko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

@file:Suppress("KDocMissingDocumentation", "unused")

package org.wysko.midis2jam2.ui.common.material

import androidx.compose.ui.graphics.Color

val primaryLight: Color = Color(0xFF4C662B)
val onPrimaryLight: Color = Color(0xFFFFFFFF)
val primaryContainerLight: Color = Color(0xFFCDEDA3)
val onPrimaryContainerLight: Color = Color(0xFF354E16)
val secondaryLight: Color = Color(0xFF586249)
val onSecondaryLight: Color = Color(0xFFFFFFFF)
val secondaryContainerLight: Color = Color(0xFFDCE7C8)
val onSecondaryContainerLight: Color = Color(0xFF404A33)
val tertiaryLight: Color = Color(0xFF386663)
val onTertiaryLight: Color = Color(0xFFFFFFFF)
val tertiaryContainerLight: Color = Color(0xFFBCECE7)
val onTertiaryContainerLight: Color = Color(0xFF1F4E4B)
val errorLight: Color = Color(0xFFBA1A1A)
val onErrorLight: Color = Color(0xFFFFFFFF)
val errorContainerLight: Color = Color(0xFFFFDAD6)
val onErrorContainerLight: Color = Color(0xFF93000A)
val backgroundLight: Color = Color(0xFFF9FAEF)
val onBackgroundLight: Color = Color(0xFF1A1C16)
val surfaceLight: Color = Color(0xFFF9FAEF)
val onSurfaceLight: Color = Color(0xFF1A1C16)
val surfaceVariantLight: Color = Color(0xFFE1E4D5)
val onSurfaceVariantLight: Color = Color(0xFF44483D)
val outlineLight: Color = Color(0xFF75796C)
val outlineVariantLight: Color = Color(0xFFC5C8BA)
val scrimLight: Color = Color(0xFF000000)
val inverseSurfaceLight: Color = Color(0xFF2F312A)
val inverseOnSurfaceLight: Color = Color(0xFFF1F2E6)
val inversePrimaryLight: Color = Color(0xFFB1D18A)
val surfaceDimLight: Color = Color(0xFFDADBD0)
val surfaceBrightLight: Color = Color(0xFFF9FAEF)
val surfaceContainerLowestLight: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLight: Color = Color(0xFFF3F4E9)
val surfaceContainerLight: Color = Color(0xFFEEEFE3)
val surfaceContainerHighLight: Color = Color(0xFFE8E9DE)
val surfaceContainerHighestLight: Color = Color(0xFFE2E3D8)

val primaryLightMediumContrast: Color = Color(0xFF253D05)
val onPrimaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast: Color = Color(0xFF5A7539)
val onPrimaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val secondaryLightMediumContrast: Color = Color(0xFF303924)
val onSecondaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast: Color = Color(0xFF667157)
val onSecondaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast: Color = Color(0xFF083D3A)
val onTertiaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast: Color = Color(0xFF477572)
val onTertiaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val errorLightMediumContrast: Color = Color(0xFF740006)
val onErrorLightMediumContrast: Color = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast: Color = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val backgroundLightMediumContrast: Color = Color(0xFFF9FAEF)
val onBackgroundLightMediumContrast: Color = Color(0xFF1A1C16)
val surfaceLightMediumContrast: Color = Color(0xFFF9FAEF)
val onSurfaceLightMediumContrast: Color = Color(0xFF0F120C)
val surfaceVariantLightMediumContrast: Color = Color(0xFFE1E4D5)
val onSurfaceVariantLightMediumContrast: Color = Color(0xFF34382D)
val outlineLightMediumContrast: Color = Color(0xFF505449)
val outlineVariantLightMediumContrast: Color = Color(0xFF6B6F62)
val scrimLightMediumContrast: Color = Color(0xFF000000)
val inverseSurfaceLightMediumContrast: Color = Color(0xFF2F312A)
val inverseOnSurfaceLightMediumContrast: Color = Color(0xFFF1F2E6)
val inversePrimaryLightMediumContrast: Color = Color(0xFFB1D18A)
val surfaceDimLightMediumContrast: Color = Color(0xFFC6C7BD)
val surfaceBrightLightMediumContrast: Color = Color(0xFFF9FAEF)
val surfaceContainerLowestLightMediumContrast: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast: Color = Color(0xFFF3F4E9)
val surfaceContainerLightMediumContrast: Color = Color(0xFFE8E9DE)
val surfaceContainerHighLightMediumContrast: Color = Color(0xFFDCDED3)
val surfaceContainerHighestLightMediumContrast: Color = Color(0xFFD1D3C8)

val primaryLightHighContrast: Color = Color(0xFF1C3200)
val onPrimaryLightHighContrast: Color = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast: Color = Color(0xFF375018)
val onPrimaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val secondaryLightHighContrast: Color = Color(0xFF262F1A)
val onSecondaryLightHighContrast: Color = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast: Color = Color(0xFF434C35)
val onSecondaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val tertiaryLightHighContrast: Color = Color(0xFF003230)
val onTertiaryLightHighContrast: Color = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast: Color = Color(0xFF21504E)
val onTertiaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val errorLightHighContrast: Color = Color(0xFF600004)
val onErrorLightHighContrast: Color = Color(0xFFFFFFFF)
val errorContainerLightHighContrast: Color = Color(0xFF98000A)
val onErrorContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val backgroundLightHighContrast: Color = Color(0xFFF9FAEF)
val onBackgroundLightHighContrast: Color = Color(0xFF1A1C16)
val surfaceLightHighContrast: Color = Color(0xFFF9FAEF)
val onSurfaceLightHighContrast: Color = Color(0xFF000000)
val surfaceVariantLightHighContrast: Color = Color(0xFFE1E4D5)
val onSurfaceVariantLightHighContrast: Color = Color(0xFF000000)
val outlineLightHighContrast: Color = Color(0xFF2A2D24)
val outlineVariantLightHighContrast: Color = Color(0xFF474B40)
val scrimLightHighContrast: Color = Color(0xFF000000)
val inverseSurfaceLightHighContrast: Color = Color(0xFF2F312A)
val inverseOnSurfaceLightHighContrast: Color = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast: Color = Color(0xFFB1D18A)
val surfaceDimLightHighContrast: Color = Color(0xFFB8BAAF)
val surfaceBrightLightHighContrast: Color = Color(0xFFF9FAEF)
val surfaceContainerLowestLightHighContrast: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast: Color = Color(0xFFF1F2E6)
val surfaceContainerLightHighContrast: Color = Color(0xFFE2E3D8)
val surfaceContainerHighLightHighContrast: Color = Color(0xFFD4D5CA)
val surfaceContainerHighestLightHighContrast: Color = Color(0xFFC6C7BD)

val primaryDark: Color = Color(0xFFB1D18A)
val onPrimaryDark: Color = Color(0xFF1F3701)
val primaryContainerDark: Color = Color(0xFF354E16)
val onPrimaryContainerDark: Color = Color(0xFFCDEDA3)
val secondaryDark: Color = Color(0xFFBFCBAD)
val onSecondaryDark: Color = Color(0xFF2A331E)
val secondaryContainerDark: Color = Color(0xFF404A33)
val onSecondaryContainerDark: Color = Color(0xFFDCE7C8)
val tertiaryDark: Color = Color(0xFFA0D0CB)
val onTertiaryDark: Color = Color(0xFF003735)
val tertiaryContainerDark: Color = Color(0xFF1F4E4B)
val onTertiaryContainerDark: Color = Color(0xFFBCECE7)
val errorDark: Color = Color(0xFFFFB4AB)
val onErrorDark: Color = Color(0xFF690005)
val errorContainerDark: Color = Color(0xFF93000A)
val onErrorContainerDark: Color = Color(0xFFFFDAD6)
val backgroundDark: Color = Color(0xFF12140E)
val onBackgroundDark: Color = Color(0xFFE2E3D8)
val surfaceDark: Color = Color(0xFF12140E)
val onSurfaceDark: Color = Color(0xFFE2E3D8)
val surfaceVariantDark: Color = Color(0xFF44483D)
val onSurfaceVariantDark: Color = Color(0xFFC5C8BA)
val outlineDark: Color = Color(0xFF8F9285)
val outlineVariantDark: Color = Color(0xFF44483D)
val scrimDark: Color = Color(0xFF000000)
val inverseSurfaceDark: Color = Color(0xFFE2E3D8)
val inverseOnSurfaceDark: Color = Color(0xFF2F312A)
val inversePrimaryDark: Color = Color(0xFF4C662B)
val surfaceDimDark: Color = Color(0xFF12140E)
val surfaceBrightDark: Color = Color(0xFF383A32)
val surfaceContainerLowestDark: Color = Color(0xFF0C0F09)
val surfaceContainerLowDark: Color = Color(0xFF1A1C16)
val surfaceContainerDark: Color = Color(0xFF1E201A)
val surfaceContainerHighDark: Color = Color(0xFF282B24)
val surfaceContainerHighestDark: Color = Color(0xFF33362E)

val primaryDarkMediumContrast: Color = Color(0xFFC7E79E)
val onPrimaryDarkMediumContrast: Color = Color(0xFF172B00)
val primaryContainerDarkMediumContrast: Color = Color(0xFF7D9A59)
val onPrimaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val secondaryDarkMediumContrast: Color = Color(0xFFD5E1C2)
val onSecondaryDarkMediumContrast: Color = Color(0xFF1F2814)
val secondaryContainerDarkMediumContrast: Color = Color(0xFF8A9579)
val onSecondaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val tertiaryDarkMediumContrast: Color = Color(0xFFB5E6E1)
val onTertiaryDarkMediumContrast: Color = Color(0xFF002B29)
val tertiaryContainerDarkMediumContrast: Color = Color(0xFF6B9995)
val onTertiaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val errorDarkMediumContrast: Color = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast: Color = Color(0xFF540003)
val errorContainerDarkMediumContrast: Color = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast: Color = Color(0xFF000000)
val backgroundDarkMediumContrast: Color = Color(0xFF12140E)
val onBackgroundDarkMediumContrast: Color = Color(0xFFE2E3D8)
val surfaceDarkMediumContrast: Color = Color(0xFF12140E)
val onSurfaceDarkMediumContrast: Color = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast: Color = Color(0xFF44483D)
val onSurfaceVariantDarkMediumContrast: Color = Color(0xFFDBDECF)
val outlineDarkMediumContrast: Color = Color(0xFFB0B3A6)
val outlineVariantDarkMediumContrast: Color = Color(0xFF8E9285)
val scrimDarkMediumContrast: Color = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast: Color = Color(0xFFE2E3D8)
val inverseOnSurfaceDarkMediumContrast: Color = Color(0xFF282B24)
val inversePrimaryDarkMediumContrast: Color = Color(0xFF364F17)
val surfaceDimDarkMediumContrast: Color = Color(0xFF12140E)
val surfaceBrightDarkMediumContrast: Color = Color(0xFF43453D)
val surfaceContainerLowestDarkMediumContrast: Color = Color(0xFF060804)
val surfaceContainerLowDarkMediumContrast: Color = Color(0xFF1C1E18)
val surfaceContainerDarkMediumContrast: Color = Color(0xFF262922)
val surfaceContainerHighDarkMediumContrast: Color = Color(0xFF31342C)
val surfaceContainerHighestDarkMediumContrast: Color = Color(0xFF3C3F37)

val primaryDarkHighContrast: Color = Color(0xFFDAFBB0)
val onPrimaryDarkHighContrast: Color = Color(0xFF000000)
val primaryContainerDarkHighContrast: Color = Color(0xFFADCD86)
val onPrimaryContainerDarkHighContrast: Color = Color(0xFF050E00)
val secondaryDarkHighContrast: Color = Color(0xFFE9F4D5)
val onSecondaryDarkHighContrast: Color = Color(0xFF000000)
val secondaryContainerDarkHighContrast: Color = Color(0xFFBCC7A9)
val onSecondaryContainerDarkHighContrast: Color = Color(0xFF060D01)
val tertiaryDarkHighContrast: Color = Color(0xFFC9F9F5)
val onTertiaryDarkHighContrast: Color = Color(0xFF000000)
val tertiaryContainerDarkHighContrast: Color = Color(0xFF9CCCC7)
val onTertiaryContainerDarkHighContrast: Color = Color(0xFF000E0D)
val errorDarkHighContrast: Color = Color(0xFFFFECE9)
val onErrorDarkHighContrast: Color = Color(0xFF000000)
val errorContainerDarkHighContrast: Color = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast: Color = Color(0xFF220001)
val backgroundDarkHighContrast: Color = Color(0xFF12140E)
val onBackgroundDarkHighContrast: Color = Color(0xFFE2E3D8)
val surfaceDarkHighContrast: Color = Color(0xFF12140E)
val onSurfaceDarkHighContrast: Color = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast: Color = Color(0xFF44483D)
val onSurfaceVariantDarkHighContrast: Color = Color(0xFFFFFFFF)
val outlineDarkHighContrast: Color = Color(0xFFEEF2E2)
val outlineVariantDarkHighContrast: Color = Color(0xFFC1C4B6)
val scrimDarkHighContrast: Color = Color(0xFF000000)
val inverseSurfaceDarkHighContrast: Color = Color(0xFFE2E3D8)
val inverseOnSurfaceDarkHighContrast: Color = Color(0xFF000000)
val inversePrimaryDarkHighContrast: Color = Color(0xFF364F17)
val surfaceDimDarkHighContrast: Color = Color(0xFF12140E)
val surfaceBrightDarkHighContrast: Color = Color(0xFF4F5149)
val surfaceContainerLowestDarkHighContrast: Color = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast: Color = Color(0xFF1E201A)
val surfaceContainerDarkHighContrast: Color = Color(0xFF2F312A)
val surfaceContainerHighDarkHighContrast: Color = Color(0xFF3A3C35)
val surfaceContainerHighestDarkHighContrast: Color = Color(0xFF454840)
