/*
 * Copyright (C) 2025 Jacob Wysko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses/.
 */

@file:Suppress("KDocMissingDocumentation", "unused")

package org.wysko.midis2jam2.gui.material

import androidx.compose.ui.graphics.Color

val primaryLight: Color = Color(0xFF3B6939)
val onPrimaryLight: Color = Color(0xFFFFFFFF)
val primaryContainerLight: Color = Color(0xFFBCF0B4)
val onPrimaryContainerLight: Color = Color(0xFF002204)
val secondaryLight: Color = Color(0xFF30628C)
val onSecondaryLight: Color = Color(0xFFFFFFFF)
val secondaryContainerLight: Color = Color(0xFFCFE5FF)
val onSecondaryContainerLight: Color = Color(0xFF001D33)
val tertiaryLight: Color = Color(0xFF38656A)
val onTertiaryLight: Color = Color(0xFFFFFFFF)
val tertiaryContainerLight: Color = Color(0xFFBCEBF0)
val onTertiaryContainerLight: Color = Color(0xFF002023)
val errorLight: Color = Color(0xFFBA1A1A)
val onErrorLight: Color = Color(0xFFFFFFFF)
val errorContainerLight: Color = Color(0xFFFFDAD6)
val onErrorContainerLight: Color = Color(0xFF410002)
val backgroundLight: Color = Color(0xFFF7FBF1)
val onBackgroundLight: Color = Color(0xFF191D17)
val surfaceLight: Color = Color(0xFFF7FBF1)
val onSurfaceLight: Color = Color(0xFF191D17)
val surfaceVariantLight: Color = Color(0xFFDEE5D8)
val onSurfaceVariantLight: Color = Color(0xFF424940)
val outlineLight: Color = Color(0xFF72796F)
val outlineVariantLight: Color = Color(0xFFC2C9BD)
val scrimLight: Color = Color(0xFF000000)
val inverseSurfaceLight: Color = Color(0xFF2D322C)
val inverseOnSurfaceLight: Color = Color(0xFFEFF2E9)
val inversePrimaryLight: Color = Color(0xFFA1D39A)
val surfaceDimLight: Color = Color(0xFFD8DBD2)
val surfaceBrightLight: Color = Color(0xFFF7FBF1)
val surfaceContainerLowestLight: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLight: Color = Color(0xFFF1F5EC)
val surfaceContainerLight: Color = Color(0xFFECEFE6)
val surfaceContainerHighLight: Color = Color(0xFFE6E9E0)
val surfaceContainerHighestLight: Color = Color(0xFFE0E4DB)

val primaryLightMediumContrast: Color = Color(0xFF1F4C20)
val onPrimaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast: Color = Color(0xFF517F4E)
val onPrimaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val secondaryLightMediumContrast: Color = Color(0xFF08466F)
val onSecondaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast: Color = Color(0xFF4978A4)
val onSecondaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast: Color = Color(0xFF1A494E)
val onTertiaryLightMediumContrast: Color = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast: Color = Color(0xFF4F7C81)
val onTertiaryContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val errorLightMediumContrast: Color = Color(0xFF8C0009)
val onErrorLightMediumContrast: Color = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast: Color = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast: Color = Color(0xFFFFFFFF)
val backgroundLightMediumContrast: Color = Color(0xFFF7FBF1)
val onBackgroundLightMediumContrast: Color = Color(0xFF191D17)
val surfaceLightMediumContrast: Color = Color(0xFFF7FBF1)
val onSurfaceLightMediumContrast: Color = Color(0xFF191D17)
val surfaceVariantLightMediumContrast: Color = Color(0xFFDEE5D8)
val onSurfaceVariantLightMediumContrast: Color = Color(0xFF3E453C)
val outlineLightMediumContrast: Color = Color(0xFF5A6157)
val outlineVariantLightMediumContrast: Color = Color(0xFF767D72)
val scrimLightMediumContrast: Color = Color(0xFF000000)
val inverseSurfaceLightMediumContrast: Color = Color(0xFF2D322C)
val inverseOnSurfaceLightMediumContrast: Color = Color(0xFFEFF2E9)
val inversePrimaryLightMediumContrast: Color = Color(0xFFA1D39A)
val surfaceDimLightMediumContrast: Color = Color(0xFFD8DBD2)
val surfaceBrightLightMediumContrast: Color = Color(0xFFF7FBF1)
val surfaceContainerLowestLightMediumContrast: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast: Color = Color(0xFFF1F5EC)
val surfaceContainerLightMediumContrast: Color = Color(0xFFECEFE6)
val surfaceContainerHighLightMediumContrast: Color = Color(0xFFE6E9E0)
val surfaceContainerHighestLightMediumContrast: Color = Color(0xFFE0E4DB)

val primaryLightHighContrast: Color = Color(0xFF002905)
val onPrimaryLightHighContrast: Color = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast: Color = Color(0xFF1F4C20)
val onPrimaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val secondaryLightHighContrast: Color = Color(0xFF00243E)
val onSecondaryLightHighContrast: Color = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast: Color = Color(0xFF08466F)
val onSecondaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val tertiaryLightHighContrast: Color = Color(0xFF00272A)
val onTertiaryLightHighContrast: Color = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast: Color = Color(0xFF1A494E)
val onTertiaryContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val errorLightHighContrast: Color = Color(0xFF4E0002)
val onErrorLightHighContrast: Color = Color(0xFFFFFFFF)
val errorContainerLightHighContrast: Color = Color(0xFF8C0009)
val onErrorContainerLightHighContrast: Color = Color(0xFFFFFFFF)
val backgroundLightHighContrast: Color = Color(0xFFF7FBF1)
val onBackgroundLightHighContrast: Color = Color(0xFF191D17)
val surfaceLightHighContrast: Color = Color(0xFFF7FBF1)
val onSurfaceLightHighContrast: Color = Color(0xFF000000)
val surfaceVariantLightHighContrast: Color = Color(0xFFDEE5D8)
val onSurfaceVariantLightHighContrast: Color = Color(0xFF1F261E)
val outlineLightHighContrast: Color = Color(0xFF3E453C)
val outlineVariantLightHighContrast: Color = Color(0xFF3E453C)
val scrimLightHighContrast: Color = Color(0xFF000000)
val inverseSurfaceLightHighContrast: Color = Color(0xFF2D322C)
val inverseOnSurfaceLightHighContrast: Color = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast: Color = Color(0xFFC5FABD)
val surfaceDimLightHighContrast: Color = Color(0xFFD8DBD2)
val surfaceBrightLightHighContrast: Color = Color(0xFFF7FBF1)
val surfaceContainerLowestLightHighContrast: Color = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast: Color = Color(0xFFF1F5EC)
val surfaceContainerLightHighContrast: Color = Color(0xFFECEFE6)
val surfaceContainerHighLightHighContrast: Color = Color(0xFFE6E9E0)
val surfaceContainerHighestLightHighContrast: Color = Color(0xFFE0E4DB)

val primaryDark: Color = Color(0xFFA1D39A)
val onPrimaryDark: Color = Color(0xFF0A390F)
val primaryContainerDark: Color = Color(0xFF235024)
val onPrimaryContainerDark: Color = Color(0xFFBCF0B4)
val secondaryDark: Color = Color(0xFF9CCBFB)
val onSecondaryDark: Color = Color(0xFF003354)
val secondaryContainerDark: Color = Color(0xFF104A73)
val onSecondaryContainerDark: Color = Color(0xFFCFE5FF)
val tertiaryDark: Color = Color(0xFFA0CFD4)
val onTertiaryDark: Color = Color(0xFF00363B)
val tertiaryContainerDark: Color = Color(0xFF1F4D52)
val onTertiaryContainerDark: Color = Color(0xFFBCEBF0)
val errorDark: Color = Color(0xFFFFB4AB)
val onErrorDark: Color = Color(0xFF690005)
val errorContainerDark: Color = Color(0xFF93000A)
val onErrorContainerDark: Color = Color(0xFFFFDAD6)
val backgroundDark: Color = Color(0xFF10140F)
val onBackgroundDark: Color = Color(0xFFE0E4DB)
val surfaceDark: Color = Color(0xFF10140F)
val onSurfaceDark: Color = Color(0xFFE0E4DB)
val surfaceVariantDark: Color = Color(0xFF424940)
val onSurfaceVariantDark: Color = Color(0xFFC2C9BD)
val outlineDark: Color = Color(0xFF8C9388)
val outlineVariantDark: Color = Color(0xFF424940)
val scrimDark: Color = Color(0xFF000000)
val inverseSurfaceDark: Color = Color(0xFFE0E4DB)
val inverseOnSurfaceDark: Color = Color(0xFF2D322C)
val inversePrimaryDark: Color = Color(0xFF3B6939)
val surfaceDimDark: Color = Color(0xFF10140F)
val surfaceBrightDark: Color = Color(0xFF363A34)
val surfaceContainerLowestDark: Color = Color(0xFF0B0F0A)
val surfaceContainerLowDark: Color = Color(0xFF191D17)
val surfaceContainerDark: Color = Color(0xFF1D211B)
val surfaceContainerHighDark: Color = Color(0xFF272B25)
val surfaceContainerHighestDark: Color = Color(0xFF323630)

val primaryDarkMediumContrast: Color = Color(0xFFA5D89E)
val onPrimaryDarkMediumContrast: Color = Color(0xFF001B03)
val primaryContainerDarkMediumContrast: Color = Color(0xFF6C9C68)
val onPrimaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val secondaryDarkMediumContrast: Color = Color(0xFFA1CFFF)
val onSecondaryDarkMediumContrast: Color = Color(0xFF00182B)
val secondaryContainerDarkMediumContrast: Color = Color(0xFF6695C2)
val onSecondaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val tertiaryDarkMediumContrast: Color = Color(0xFFA5D3D8)
val onTertiaryDarkMediumContrast: Color = Color(0xFF001A1C)
val tertiaryContainerDarkMediumContrast: Color = Color(0xFF6B989E)
val onTertiaryContainerDarkMediumContrast: Color = Color(0xFF000000)
val errorDarkMediumContrast: Color = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast: Color = Color(0xFF370001)
val errorContainerDarkMediumContrast: Color = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast: Color = Color(0xFF000000)
val backgroundDarkMediumContrast: Color = Color(0xFF10140F)
val onBackgroundDarkMediumContrast: Color = Color(0xFFE0E4DB)
val surfaceDarkMediumContrast: Color = Color(0xFF10140F)
val onSurfaceDarkMediumContrast: Color = Color(0xFFF9FCF3)
val surfaceVariantDarkMediumContrast: Color = Color(0xFF424940)
val onSurfaceVariantDarkMediumContrast: Color = Color(0xFFC6CDC1)
val outlineDarkMediumContrast: Color = Color(0xFF9EA59A)
val outlineVariantDarkMediumContrast: Color = Color(0xFF7E857B)
val scrimDarkMediumContrast: Color = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast: Color = Color(0xFFE0E4DB)
val inverseOnSurfaceDarkMediumContrast: Color = Color(0xFF272B25)
val inversePrimaryDarkMediumContrast: Color = Color(0xFF255125)
val surfaceDimDarkMediumContrast: Color = Color(0xFF10140F)
val surfaceBrightDarkMediumContrast: Color = Color(0xFF363A34)
val surfaceContainerLowestDarkMediumContrast: Color = Color(0xFF0B0F0A)
val surfaceContainerLowDarkMediumContrast: Color = Color(0xFF191D17)
val surfaceContainerDarkMediumContrast: Color = Color(0xFF1D211B)
val surfaceContainerHighDarkMediumContrast: Color = Color(0xFF272B25)
val surfaceContainerHighestDarkMediumContrast: Color = Color(0xFF323630)

val primaryDarkHighContrast: Color = Color(0xFFF1FFEA)
val onPrimaryDarkHighContrast: Color = Color(0xFF000000)
val primaryContainerDarkHighContrast: Color = Color(0xFFA5D89E)
val onPrimaryContainerDarkHighContrast: Color = Color(0xFF000000)
val secondaryDarkHighContrast: Color = Color(0xFFFAFAFF)
val onSecondaryDarkHighContrast: Color = Color(0xFF000000)
val secondaryContainerDarkHighContrast: Color = Color(0xFFA1CFFF)
val onSecondaryContainerDarkHighContrast: Color = Color(0xFF000000)
val tertiaryDarkHighContrast: Color = Color(0xFFEFFDFF)
val onTertiaryDarkHighContrast: Color = Color(0xFF000000)
val tertiaryContainerDarkHighContrast: Color = Color(0xFFA5D3D8)
val onTertiaryContainerDarkHighContrast: Color = Color(0xFF000000)
val errorDarkHighContrast: Color = Color(0xFFFFF9F9)
val onErrorDarkHighContrast: Color = Color(0xFF000000)
val errorContainerDarkHighContrast: Color = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast: Color = Color(0xFF000000)
val backgroundDarkHighContrast: Color = Color(0xFF10140F)
val onBackgroundDarkHighContrast: Color = Color(0xFFE0E4DB)
val surfaceDarkHighContrast: Color = Color(0xFF10140F)
val onSurfaceDarkHighContrast: Color = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast: Color = Color(0xFF424940)
val onSurfaceVariantDarkHighContrast: Color = Color(0xFFF7FDF0)
val outlineDarkHighContrast: Color = Color(0xFFC6CDC1)
val outlineVariantDarkHighContrast: Color = Color(0xFFC6CDC1)
val scrimDarkHighContrast: Color = Color(0xFF000000)
val inverseSurfaceDarkHighContrast: Color = Color(0xFFE0E4DB)
val inverseOnSurfaceDarkHighContrast: Color = Color(0xFF000000)
val inversePrimaryDarkHighContrast: Color = Color(0xFF023209)
val surfaceDimDarkHighContrast: Color = Color(0xFF10140F)
val surfaceBrightDarkHighContrast: Color = Color(0xFF363A34)
val surfaceContainerLowestDarkHighContrast: Color = Color(0xFF0B0F0A)
val surfaceContainerLowDarkHighContrast: Color = Color(0xFF191D17)
val surfaceContainerDarkHighContrast: Color = Color(0xFF1D211B)
val surfaceContainerHighDarkHighContrast: Color = Color(0xFF272B25)
val surfaceContainerHighestDarkHighContrast: Color = Color(0xFF323630)

val customColorLight: Color = Color(0xFF3A608F)
val onCustomColorLight: Color = Color(0xFFFFFFFF)
val customColorContainerLight: Color = Color(0xFFD3E3FF)
val onCustomColorContainerLight: Color = Color(0xFF001C39)

val customColorLightMediumContrast: Color = Color(0xFF1B4472)
val onCustomColorLightMediumContrast: Color = Color(0xFFFFFFFF)
val customColorContainerLightMediumContrast: Color = Color(0xFF5276A7)
val onCustomColorContainerLightMediumContrast: Color = Color(0xFFFFFFFF)

val customColorLightHighContrast: Color = Color(0xFF002344)
val onCustomColorLightHighContrast: Color = Color(0xFFFFFFFF)
val customColorContainerLightHighContrast: Color = Color(0xFF1B4472)
val onCustomColorContainerLightHighContrast: Color = Color(0xFFFFFFFF)

val customColorDark: Color = Color(0xFFA4C9FE)
val onCustomColorDark: Color = Color(0xFF00315D)
val customColorContainerDark: Color = Color(0xFF204876)
val onCustomColorContainerDark: Color = Color(0xFFD3E3FF)

val customColorDarkMediumContrast: Color = Color(0xFFABCDFF)
val onCustomColorDarkMediumContrast: Color = Color(0xFF001730)
val customColorContainerDarkMediumContrast: Color = Color(0xFF6E93C5)
val onCustomColorContainerDarkMediumContrast: Color = Color(0xFF000000)

val customColorDarkHighContrast: Color = Color(0xFFFBFAFF)
val onCustomColorDarkHighContrast: Color = Color(0xFF000000)
val customColorContainerDarkHighContrast: Color = Color(0xFFABCDFF)
val onCustomColorContainerDarkHighContrast: Color = Color(0xFF000000)